name: 첫 번째 Actions 실습

on:
  push:
    branches: [ "main" ]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: 인사 출력
        run: echo "Hello! GitHub Actions 작동 중입니다"

      - name: 현재 날짜 출력
        run: date